books = [
    {'id': 0,
     'title': 'A Fire Upon the Deep',
     'author': 'Vernor Vinge',
     'first_sentence': 'The coldsleep itself was dreamless.',
     'published': '1992'},
    {'id': 1,
     'title': 'The Ones Who Walk Away From Omelas',
     'author': 'Ursula K. Le Guin',
     'first_sentence': 'With a clamor of bells that set the swallows soaring, the Festival of Summer came to the city Omelas, bright-towered by the sea.',
     'published': '1973'},
    {'id': 2,
     'title': 'Dhalgren',
     'author': 'Samuel R. Delany',
     'first_sentence': 'To wound the autumnal city.',
     'published': '1975'},
    {'id': 3,
     'title': 'Dune',
     'author': 'Frank Herbert',
     'first_sentence': 'It was a warm night at Castle Caladan, and the ancient pile of stone that had served the Atreides family as home for twenty-six generations bore that cooled-sweat feeling it acquired before a change in the weather.',
     'published': '1965'},
    {'id': 4,
     'title': 'Neuromancer',
     'author': 'William Gibson',
     'first_sentence': 'The sky above the port was the color of television, tuned to a dead channel.',
     'published': '1984'},
    {'id': 5,
     'title': 'Roadside Picnic',
     'author': 'Arkady & Boris Strugatsky',
     'first_sentence': 'FROM AN INTERVIEW BY A SPECIAL CORRESPONDENT FROM HARMONT RADIO WITH DOCTOR VALENTINE PILMAN, RECIPIENT OF THE NOBEL PRIZE IN PHYSICS FOR 19..',
     'published': '1972'},
    {'id': 6,
     'title': 'The City and the City',
     'author': 'China Miéville',
     'first_sentence': 'I could not see the street or much of the estate.',
     'published': '2009'}
]